spring.application.name=Node
server.port=${SERVER_PORT:8082}
cluster.master.host=${CLUSTER_MASTER_HOST:localhost}
cluster.master.port=${CLUSTER_MASTER_PORT:8080}
cluster.node.host=${CLUSTER_NODE_HOST:${HOSTNAME:localhost}}
cluster.registry.url=http://${cluster.master.host}:${cluster.master.port}/register
cluster.heartbeat.url=http://${cluster.master.host}:${cluster.master.port}/heartbeat